package fit.cvut.si1.semestralka.tattooPro.data.entities;

import javax.persistence.*;

/**
 * Represents a message between two users.
 */
@Entity
public class Message {
    /**
     * Autogenerated ID.
     */
    @Id
    @GeneratedValue
    private int messageID;
    /**
     * User that sent the message.
     */
    @ManyToOne
    @JoinColumn(nullable = false)
    private User sender;
    /**
     * User that received the message.
     */
    @ManyToOne
    @JoinColumn(nullable = false)
    private User receiver;
    /**
     * Text of the message.
     */
    @Column(nullable = false)
    private String messageText;
    /**
     * string of time when the message was added to database
     */
    @Column(nullable = false)
    private String timeStamp;

    /**
     * Empty message constructor.
     */
    public Message() {}
    /**
     * Message constructor with params.
     * @param sender Sender user
     * @param receiver Reciever user
     * @param messageText Message text
     */
    public Message(User sender, User receiver, String messageText) {
        this.sender = sender;
        this.receiver = receiver;
        this.messageText = messageText;
    }

    public User getSender() { return sender; }
    public void setSender(User sender) { this.sender = sender; }

    public User getReceiver() { return receiver; }
    public void setReceiver(User receiver) { this.receiver = receiver; }

    public int getMessageID() { return messageID; }
    public void setMessageID(int messageID) { this.messageID = messageID; }

    public String getMessageText() { return messageText; }
    public void setMessageText(String messageText) { this.messageText = messageText; }

    public String getTimeStamp() { return timeStamp; }

    public void setTimeStamp(String timeStamp) { this.timeStamp = timeStamp; }
}
