package fit.cvut.si1.semestralka.tattooPro.data.entities;

import javax.persistence.*;

/**
 * Image entity.
 */
@Entity
public class Image {
    /**
     * Autogenerated image ID.
     */
    @Id
    @GeneratedValue
    private int imageID;
    /**
     * Image description
     */
    private String imageDescription;
    /**
     * Image data
     * As well as in User - pictures are bigger than 255 bytes
     */
    @Column(length = 10000)
    private byte[] imageData;
    /**
     * Image owner.
     */
    @ManyToOne
    private User imageOwner;

    public int getImageID() {
        return imageID;
    }
    public void setImageID(int imageID) { this.imageID = imageID; }

    public String getImageDescription() {
        return imageDescription;
    }
    public void setImageDescription(String imageDescription) {
        this.imageDescription = imageDescription;
    }

    public byte[] getImageData() {
        return imageData;
    }
    public void setImageData(byte[] imageData) {
        this.imageData = imageData;
    }

    public User getImageOwner() {
        return imageOwner;
    }
    public void setImageOwner(User imageOwner) {
        this.imageOwner = imageOwner;
    }
}
